import { SITE_CONFIG } from '@/lib/seo/schema';

export type ProductCategory =
  | 'hematology'
  | 'biochemistry'
  | 'immunoassay'
  | 'microscopes'
  | 'lab-equipment'
  | 'consumables';

export interface ProductSpecItem {
  label: string;
  value: string;
}

export interface Product {
  id: string;
  name: string;
  model: string;
  brand: string;
  category: ProductCategory;
  subcategory: string;
  price: number | null; // null for Price on Request
  priceFormatted: string;
  tagline: string;
  description: string;
  badge?: string;
  image?: string;
  highlights: string[];
  specs: ProductSpecItem[];
  warranty?: string;
  delivery?: string;
}

export const CATEGORIES_CONFIG: {
  id: ProductCategory;
  name: string;
  shortName: string;
  description: string;
  iconName: string;
}[] = [
  {
    id: 'hematology',
    name: 'Hematology Analyzers',
    shortName: 'Hematology',
    description: 'Automated 3-part and 5-part CBC machines for complete blood counts, differential analysis, and anemia screening.',
    iconName: 'Droplet',
  },
  {
    id: 'biochemistry',
    name: 'Biochemistry Analyzers',
    shortName: 'Biochemistry',
    description: 'Semi-automated, dry chemistry microfluidic discs, and high-throughput fully automated clinical chemistry platforms.',
    iconName: 'FlaskConical',
  },
  {
    id: 'immunoassay',
    name: 'Immunoassay POCT',
    shortName: 'Immunoassay',
    description: 'Rapid Point-of-Care (POCT) fluorescence immunoassay analyzers for cardiac, thyroid, inflammation, and hormone biomarkers.',
    iconName: 'Activity',
  },
  {
    id: 'microscopes',
    name: 'Clinical Microscopes',
    shortName: 'Microscopes',
    description: 'High-precision binocular and ergonomic LED biological microscopes for parasitology, hematology, and clinical cytology.',
    iconName: 'Microscope',
  },
  {
    id: 'lab-equipment',
    name: 'Other Lab Equipment',
    shortName: 'Lab Equipment',
    description: 'Essential clinical laboratory bench machinery: incubators, brushless centrifuges, tube roller mixers, VDRL shakers, and medical fridges.',
    iconName: 'Cpu',
  },
  {
    id: 'consumables',
    name: 'Laboratory Consumables',
    shortName: 'Consumables',
    description: 'Reliable, standardized diagnostic consumables: microscope slides, cover slips, universal yellow tips, vacuum blood collection tubes, and gloves.',
    iconName: 'PackageCheck',
  },
];

export const PRODUCTS_CATALOG: Product[] = [
  // ==========================================
  // 1. HEMATOLOGY ANALYZERS - 3-PART
  // ==========================================
  {
    id: 'mindray-bc-10',
    name: 'Mindray BC-10 Automated Hematology Analyzer',
    model: 'BC-10',
    brand: 'Mindray',
    category: 'hematology',
    subcategory: '3-Part Differential',
    price: 500000,
    priceFormatted: 'KSh 500,000',
    tagline: 'Ultra-compact 3-part CBC analyzer ideal for primary clinics and dispensaries.',
    description:
      'The Mindray BC-10 is a compact, cost-effective 3-part differential automated hematology analyzer. Requiring only 9 μL of whole blood, it is engineered for community health centers, outpatient clinics, and private medical practices requiring reliable diagnostic quality without excessive bench space.',
    badge: 'Popular for Starter Clinics',
    highlights: [
      'Throughput: 30 tests/hour',
      'Ultra-low sample volume: 9 μL (whole blood)',
      '20 reportable parameters + 3 histograms',
      '8.4-inch color TFT touchscreen',
      '50,000 patient records storage',
    ],
    specs: [
      { label: 'Differential Type', value: '3-Part Differential WBC' },
      { label: 'Throughput', value: 'Up to 30 samples/hour' },
      { label: 'Sample Volume', value: '≤ 9 μL (Whole Blood), ≤ 20 μL (Pre-diluted)' },
      { label: 'Parameters', value: '20 parameters (WBC, Lymph#, Mid#, Gran#, Lymph%, Mid%, Gran%, RBC, HGB, HCT, MCV, MCH, MCHC, RDW-CV, RDW-SD, PLT, MPV, PDW, PCT, P-LCR)' },
      { label: 'Histograms', value: '3 histograms (WBC, RBC, PLT)' },
      { label: 'Measurement Principles', value: 'Electrical impedance for cell counting; Cyanide-free colorimetry for Hemoglobin (HGB)' },
      { label: 'Display & UI', value: '8.4-inch TFT color touch screen' },
      { label: 'Data Storage', value: 'Up to 50,000 sample results including numerical and graphical data' },
      { label: 'Connectivity', value: '4 USB ports, 1 LAN port, bi-directional LIS support (HL7 protocol)' },
      { label: 'Reagent System', value: 'Low reagent consumption (Diluent, Lyse, Probe Cleanser)' },
      { label: 'Weight & Dimensions', value: 'Approx. 18 kg | Compact benchtop footprint' },
    ],
    warranty: '1 Year Comprehensive Warranty + Medwise Installation & Staff Training',
    delivery: 'Available for immediate dispatch across Kenya (Kisumu, Nairobi, Eldoret, Mombasa)',
  },
  {
    id: 'zybio-z3',
    name: 'Zybio Z3 3-Part Hematology Analyzer',
    model: 'Z3',
    brand: 'Zybio',
    category: 'hematology',
    subcategory: '3-Part Differential',
    price: 450000,
    priceFormatted: 'KSh 450,000',
    tagline: 'High-speed 70 tests/hr cell counter with brilliant 10.4-inch interface.',
    description:
      'The Zybio Z3 delivers class-leading speed in the 3-part segment, processing up to 70 samples per hour with a low aspiration volume of 10 μL. Featuring an intuitive 10.4-inch HD touchscreen, low reagent consumption, and robust fluidic design, it is a proven favorite across Kenyan outpatient facilities.',
    badge: 'High Speed (70 T/H)',
    highlights: [
      'Throughput: 70 tests/hour',
      'Sample volume: 10 μL (whole blood)',
      '21 reportable parameters + 3 histograms',
      '10.4-inch color touchscreen display',
      'Lightweight design (< 20 kg)',
    ],
    specs: [
      { label: 'Differential Type', value: '3-Part Differential WBC' },
      { label: 'Throughput', value: 'Up to 70 samples/hour' },
      { label: 'Sample Volume', value: '10 μL (Whole blood mode), 20 μL (Pre-diluted mode)' },
      { label: 'Sample Types', value: 'Venous blood, capillary blood, and pre-diluted blood' },
      { label: 'Parameters', value: '21 parameters (WBC, Lym#, Mid#, Gran#, Lym%, Mid%, Gran%, RBC, HGB, HCT, MCV, MCH, MCHC, RDW-CV, RDW-SD, PLT, MPV, PDW, PCT, P-LCR, P-LCC)' },
      { label: 'Histograms', value: '3 histograms (WBC, RBC, PLT)' },
      { label: 'Measurement Principles', value: 'Electrical impedance method for cell counting; Colorimetric method for HGB' },
      { label: 'Display & UI', value: '10.4-inch responsive high-definition touchscreen' },
      { label: 'Data Storage', value: 'Up to 40,000 patient records including histograms' },
      { label: 'Connectivity', value: 'Bi-directional LIS (HL7), USB, RJ45 LAN' },
      { label: 'Weight', value: '< 20 kg' },
    ],
    warranty: '1 Year Warranty + Medwise Technical Support & QC Verification',
    delivery: 'Nationwide dispatch with engineer-led installation across Kenya',
  },
  {
    id: 'dymind-dh36',
    name: 'Dymind DH36 3-Part Hematology Analyzer',
    model: 'DH36',
    brand: 'Dymind',
    category: 'hematology',
    subcategory: '3-Part Differential',
    price: 450000,
    priceFormatted: 'KSh 450,000',
    tagline: 'Reliable 60 T/H CBC workhorse with intelligent fluidic blockage protection.',
    description:
      'The Dymind DH36 is a robust 3-part differential automated hematology analyzer built for demanding daily routine testing. It combines rapid 60 tests/hr throughput with 9 μL micro-aspiration and advanced fluidic blockage clearing, making it exceptionally reliable in rural and urban clinics alike.',
    badge: 'Reliable Workhorse',
    highlights: [
      'Throughput: 60 tests/hour',
      'Sample volume: 9 μL whole blood',
      '21 reportable parameters + 3 histograms',
      '10.4-inch color TFT touchscreen',
      '50,000 patient records storage',
    ],
    specs: [
      { label: 'Differential Type', value: '3-Part Differential WBC' },
      { label: 'Throughput', value: 'Up to 60 samples/hour' },
      { label: 'Sample Volume', value: '9 μL (Whole blood), 20 μL (Pre-diluted)' },
      { label: 'Parameters', value: '21 parameters (WBC, Gran#, Lym#, Mid#, Gran%, Lym%, Mid%, RBC, HGB, HCT, MCV, MCH, MCHC, RDW-SD, RDW-CV, PLT, MPV, PDW, PCT, P-LCC, P-LCR)' },
      { label: 'Histograms', value: '3 histograms (WBC, RBC, PLT)' },
      { label: 'Measurement Principles', value: 'Electrical impedance; Cyanide-free colorimetry for HGB' },
      { label: 'Display & UI', value: '10.4-inch color TFT touchscreen' },
      { label: 'Data Storage', value: '50,000 results with graphical histograms' },
      { label: 'Connectivity', value: '4 USB ports, 1 LAN port, bi-directional LIS integration' },
      { label: 'Dimensions & Weight', value: 'Compact benchtop | 19 kg' },
    ],
    warranty: '1 Year Official Warranty + Medwise Installation & Staff Training',
    delivery: 'Fast nationwide Kenya delivery with complete starter kit setup',
  },
  {
    id: 'bioelab-ec-30',
    name: 'Bioelab EC-30 Automated Hematology Analyzer',
    model: 'EC-30',
    brand: 'Bioelab',
    category: 'hematology',
    subcategory: '3-Part Differential',
    price: 380000,
    priceFormatted: 'KSh 380,000',
    tagline: 'Budget-friendly 3-part CBC analyzer with massive 500,000-result memory.',
    description:
      'The Bioelab EC-30 offers unmatched value for small to medium healthcare facilities establishing or upgrading their diagnostic laboratory. With 60 samples/hour throughput, 9 μL sample aspiration, built-in thermal printer, and one-key blockage removal, it delivers maximum diagnostic return on investment.',
    badge: 'Best Value Investment',
    highlights: [
      'Throughput: 60 tests/hour',
      'Sample volume: 9 μL whole blood',
      '21 reportable parameters + 3 histograms',
      '10.4-inch color touch screen',
      'Massive 500,000 result storage capacity',
    ],
    specs: [
      { label: 'Differential Type', value: '3-Part Differential WBC' },
      { label: 'Throughput', value: 'Up to 60 samples/hour' },
      { label: 'Sample Volume', value: '9 μL (Whole blood mode), 20 μL (Pre-diluted)' },
      { label: 'Parameters', value: '21 parameters (WBC, RBC, HGB, HCT, MCV, MCH, MCHC, RDW, PLT, MPV, LY%, LY#, MID%, MID#, GR%, GR#, etc.)' },
      { label: 'Histograms', value: '3 histograms (WBC, RBC, PLT)' },
      { label: 'Measurement Principles', value: 'Electrical impedance method; Cyanide-free colorimetry' },
      { label: 'Display & UI', value: '10.4-inch TFT color touch screen' },
      { label: 'Storage', value: 'Up to 500,000 records including histograms and patient details' },
      { label: 'Unclogging System', value: 'High-voltage burn, flush, and automated reverse soaking' },
      { label: 'Printer', value: 'Built-in thermal printer + external printer support' },
      { label: 'Reagent System', value: '1 Diluent + 1 Lyse (Economic running cost per test)' },
    ],
    warranty: '1 Year Warranty + Medwise Preventive Calibration Support',
    delivery: 'Delivered nationwide across Kenya with on-site calibration',
  },

  // ==========================================
  // 1. HEMATOLOGY ANALYZERS - 5-PART
  // ==========================================
  {
    id: 'mindray-bc-5000',
    name: 'Mindray BC-5000 5-Part Hematology Analyzer',
    model: 'BC-5000',
    brand: 'Mindray',
    category: 'hematology',
    subcategory: '5-Part Differential',
    price: 1000000,
    priceFormatted: 'KSh 1,000,000',
    tagline: 'Miniaturized laser flow cytometry 5-part CBC analyzer for modern hospitals.',
    description:
      'The Mindray BC-5000 is an advanced 5-part differential hematology analyzer that packages Tri-angle Laser Scatter and semiconductor flow cytometry into a miniature desktop footprint. Requiring only 15 μL of blood, it is ideal for Level 4/5 hospitals, referral laboratories, and pediatric centers requiring high clinical specificity.',
    badge: 'Laser Flow Cytometry',
    highlights: [
      'Throughput: 40 tests/hour',
      'Sample volume: Only 15 μL (whole blood / capillary)',
      '23 reportable parameters + 3D scattergrams',
      'Tri-angle laser scatter + chemical dye technology',
      'Compact benchtop space-saving design',
    ],
    specs: [
      { label: 'Differential Type', value: '5-Part Differential (Neutrophils, Lymphocytes, Monocytes, Eosinophils, Basophils)' },
      { label: 'Throughput', value: 'Up to 40 samples/hour' },
      { label: 'Sample Volume', value: '15 μL (Whole blood / Capillary), 20 μL (Pre-diluted)' },
      { label: 'Parameters', value: '23 parameters: WBC, Lym%, Mon%, Neu%, Bas%, Eos%, Lym#, Mon#, Neu#, Bas#, Eos#, RBC, HGB, HCT, MCV, MCH, MCHC, RDW-CV, RDW-SD, PLT, MPV, PDW, PCT' },
      { label: 'Scattergrams & Histograms', value: '3 scattergrams (for WBC differentiation) + 3 histograms (WBC, RBC, PLT)' },
      { label: 'Measurement Principles', value: 'Tri-angle Laser Scatter + Chemical Dye + Flow Cytometry for WBC; Impedance for RBC & PLT' },
      { label: 'Display & UI', value: '10.4-inch color TFT touch screen' },
      { label: 'Data Storage', value: 'Up to 20,000 sample results including numerical and graphical data' },
      { label: 'Connectivity', value: 'LAN port (HL7 protocol for LIS/HIS), USB ports' },
      { label: 'Reagent Management', value: 'On-board RFID reagent tracking with 3 routine reagents' },
    ],
    warranty: '1 Year Full Warranty + Medwise Professional Metrological Calibration',
    delivery: 'Nationwide Kenyan delivery with hands-on biomedical engineer installation',
  },
  {
    id: 'zybio-z50',
    name: 'Zybio Z50 5-Part Hematology Analyzer',
    model: 'Z50',
    brand: 'Zybio',
    category: 'hematology',
    subcategory: '5-Part Differential',
    price: 900000,
    priceFormatted: 'KSh 900,000',
    tagline: '60 T/H 5-part differential analyzer with 29 reportable parameters & dedicated basophil channel.',
    description:
      'The Zybio Z50 delivers high-throughput 60 tests/hour 5-part WBC differentiation using tri-angle laser scatter and flow cytometry. Engineered with a dedicated optical channel for basophils and 29 parameters, it provides referral-grade diagnostic accuracy for busy Kenyan hospitals and clinical laboratories.',
    badge: '29 Parameters + 60 T/H',
    highlights: [
      'Throughput: 60 tests/hour',
      'Sample volume: 18 μL whole blood',
      '29 reportable parameters + 5 scattergrams + 3 histograms',
      'Dedicated basophil optical measurement channel',
      'Intelligent abnormal morphology alert flags',
    ],
    specs: [
      { label: 'Differential Type', value: '5-Part Differential WBC' },
      { label: 'Throughput', value: 'Up to 60 samples/hour' },
      { label: 'Sample Volume', value: '18 μL (Whole blood, capillary, pre-diluted modes)' },
      { label: 'Parameters', value: '29 reportable parameters including complete 5-part subpopulation counts & percentages' },
      { label: 'Graphics', value: '5 scattergrams (WBC differentiation & eosinophil isolation) + 3 histograms' },
      { label: 'Technology', value: 'Tri-angle laser scatter + Flow cytometry + Chemical dye method' },
      { label: 'Basophil Channel', value: 'Dedicated optical measurement channel for superior basophil accuracy' },
      { label: 'Display & UI', value: '10.4-inch high-resolution touch screen' },
      { label: 'Storage', value: 'Up to 50,000 patient records with complete scattergrams' },
      { label: 'Connectivity', value: 'Bi-directional LIS (HL7), USB, RJ45 LAN' },
    ],
    warranty: '1 Year Warranty + Medwise Preventive Maintenance & Training',
    delivery: 'Supplied and commissioned across Kenya (Nairobi, Kisumu, Nakuru, Eldoret)',
  },
  {
    id: 'dymind-df-55',
    name: 'Dymind DF 55 5-Part Hematology Analyzer',
    model: 'DF 55',
    brand: 'Dymind',
    category: 'hematology',
    subcategory: '5-Part Differential',
    price: 900000,
    priceFormatted: 'KSh 900,000',
    tagline: 'High-speed 60 T/H 5-part analyzer with 25 diagnostic + 6 research parameters.',
    description:
      'The Dymind DF 55 is a precision 5-part hematology analyzer built with flow cytometry (FCM) and tri-angle laser scatter. Capable of analyzing 60 samples per hour with 20 μL aspiration, it offers 25 diagnostic parameters plus 6 advanced research parameters (including NRBC & immature cells), backed by 100,000-record storage.',
    badge: '25+6 Parameters (NRBC)',
    highlights: [
      'Throughput: 60 tests/hour',
      'Sample volume: 20 μL',
      '25 reportable parameters + 6 research parameters (NRBC, LIC, ALY)',
      '100,000 patient records storage',
      'Tri-angle semiconductor laser scatter',
    ],
    specs: [
      { label: 'Differential Type', value: '5-Part Differential WBC' },
      { label: 'Throughput', value: 'Up to 60 tests/hour' },
      { label: 'Sample Volume', value: '20 μL (Whole blood, capillary, pre-diluted)' },
      { label: 'Diagnostic Parameters', value: '25 parameters (WBC, Neu#, Lym#, Mon#, Eos#, Bas#, Neu%, Lym%, Mon%, Eos%, Bas%, RBC, HGB, HCT, MCV, MCH, MCHC, RDW-SD, RDW-CV, PLT, MPV, PDW, PCT, P-LCR, P-LCC)' },
      { label: 'Research Parameters', value: '6 parameters: ALY#, ALY%, LIC#, LIC%, NRBC#, NRBC%' },
      { label: 'Technology', value: 'Flow Cytometry (FCM) + Tri-angle Laser Scatter + Cyanide-free HGB' },
      { label: 'Display', value: '10.4-inch TFT color touchscreen' },
      { label: 'Data Capacity', value: 'Up to 100,000 records including all graphs' },
      { label: 'Connectivity', value: '4 USB ports, 1 LAN port, bi-directional LIS (HL7)' },
      { label: 'Dimensions & Weight', value: '364mm (W) × 498mm (H) × 431mm (D) | 28 kg' },
    ],
    warranty: '1 Year Warranty + Medwise Quality Control & Verification Setup',
    delivery: 'Countrywide Kenyan logistics, calibration, and hands-on staff orientation',
  },

  // ==========================================
  // 2. BIOCHEMISTRY - SEMI-AUTOMATED
  // ==========================================
  {
    id: 'icubio-ichem-535',
    name: 'Icubio iChem-535 Semi-Automated Chemistry Analyzer',
    model: 'iChem-535',
    brand: 'Icubio',
    category: 'biochemistry',
    subcategory: 'Semi-Automated Biochemistry',
    price: 170000,
    priceFormatted: 'KSh 170,000',
    tagline: 'High-precision quartz flow cell photometer with built-in multi-temperature incubator.',
    description:
      'The Icubio iChem-535 is an exceptionally reliable semi-automated clinical chemistry analyzer designed for entry-level clinics, dispensaries, and private medical laboratories. Featuring a 32 μL quartz glass flow cell, 7 standard optical filters (340–630 nm), and an integrated incubator, it handles Liver, Kidney, Lipid, and Cardiac profiles with ease.',
    badge: 'Affordable Starter Analyzer',
    highlights: [
      '7 standard optical filters (340–630 nm) + 1 free slot',
      'High-grade quartz flow cell (32 μL) + cuvette mode',
      'Built-in multi-temperature incubator (25°C, 30°C, 37°C)',
      '7-inch color LCD touchscreen',
      '10,000 patient test results storage',
    ],
    specs: [
      { label: 'Analyzer Type', value: 'Semi-Automated Clinical Biochemistry Photometer' },
      { label: 'Wavelengths', value: '7 standard filters: 340, 405, 492, 510, 546, 578, 630 nm (±2 nm precision) + 1 optional position' },
      { label: 'Light Source', value: 'Philips 6V 10W long-life halogen lamp with auto-hibernate' },
      { label: 'Flow Cell', value: '32 μL quartz glass flow cell with 10 mm optical path length (Supports both flow cell & cuvette)' },
      { label: 'Assay Methods', value: 'End point, Fixed-time (Two-point), Kinetic, Absorbance' },
      { label: 'Absorbance Range', value: '0.000 to 4.500 Abs' },
      { label: 'Incubator', value: 'Integrated multi-position incubator with ±0.1°C precision' },
      { label: 'Display & UI', value: '7-inch color LCD touchscreen' },
      { label: 'Memory', value: '10,000 sample test records' },
      { label: 'Printer', value: 'Built-in high-speed thermal printer' },
    ],
    warranty: '1 Year Warranty + Medwise Micropipetting & QC Protocol Training',
    delivery: 'Nationwide dispatch with starter calibration buffer assistance',
  },
  {
    id: 'dymind-dp-c16',
    name: 'Dymind DP-C16 Semi-Automated Chemistry & Coagulation Analyzer',
    model: 'DP-C16',
    brand: 'Dymind',
    category: 'biochemistry',
    subcategory: 'Semi-Automated Biochemistry',
    price: 170000,
    priceFormatted: 'KSh 170,000',
    tagline: 'Dual-purpose biochemistry & coagulation analyzer with 8 wavelengths.',
    description:
      'The Dymind DP-C16 offers unique dual functionality: high-accuracy clinical chemistry photometry combined with integrated blood coagulation testing (PT, APTT, TT, FIB). With 8 wavelengths (340–660 nm), 300,000-record storage, and compact 6 kg portability, it maximizes diagnostic scope for upcoming clinics.',
    badge: 'Chemistry + Coagulation',
    highlights: [
      'Dual capability: Biochemistry + Coagulation tests',
      '8 optical wavelengths (340 to 660 nm)',
      'Low reaction volume: 200 μL flow cell / 150 μL coagulation',
      '7-inch responsive color touch screen',
      '300,000 test records memory & LIS cloud integration',
    ],
    specs: [
      { label: 'Analyzer Type', value: 'Semi-Automated Biochemistry & Coagulation Analyzer' },
      { label: 'Wavelengths', value: '8 filters: 340, 405, 510, 546, 578, 600, 630, 660 nm' },
      { label: 'Measurement Principles', value: 'Colorimetry, Immunoturbidimetry, and Optical Coagulation' },
      { label: 'Reaction Volume', value: 'Flow Cell: 200 μL | Coagulation Channel: 150 μL' },
      { label: 'Light Source', value: '6V 10W Halogen lamp with narrow-band interference filter' },
      { label: 'Display & UI', value: '7-inch color touchscreen interface' },
      { label: 'Memory Capacity', value: 'Up to 300,000 patient test records' },
      { label: 'Connectivity', value: '4 USB ports, 1 LAN port, bi-directional LIS & Dymind-Cloud' },
      { label: 'Dimensions & Weight', value: '336 mm × 182 mm × 318 mm | Weight ≤ 6 kg' },
    ],
    warranty: '1 Year Warranty + Medwise Technical Setup & Reagent Guidance',
    delivery: 'Supplied directly across Kenya with full operational training',
  },

  // ==========================================
  // 2. BIOCHEMISTRY - DRY CHEMISTRY
  // ==========================================
  {
    id: 'seamaty-sd-1',
    name: 'Seamaty SD 1 Automated Dry Chemistry Analyzer',
    model: 'SD 1',
    brand: 'Seamaty',
    category: 'biochemistry',
    subcategory: 'Dry Chemistry',
    price: 450000,
    priceFormatted: 'KSh 450,000',
    tagline: 'Zero reagent waste microfluidic disc analyzer delivering full profiles in 12 minutes.',
    description:
      'The Seamaty SD 1 revolutionizes clinical biochemistry for specialist clinics, mobile medical camps, and low-to-medium volume centers. Utilizing single-use microfluidic reagent discs containing lyophilized beads, it tests 19+ parameters (including enzymes and electrolytes) in just 12 minutes from 100 μL of whole blood—with zero liquid reagent expiry waste.',
    badge: 'Zero Liquid Reagent Waste',
    highlights: [
      'Rapid turnaround: Complete panel in 12 minutes',
      'Micro-sample: 90–120 μL (Whole blood, serum, or plasma)',
      'Pre-packaged panels: Liver, Renal, Electrolytes, Lipids, Cardiac',
      'Zero liquid waste & zero electronic countdown expiry loss',
      'Lightweight & portable: 4.6 kg with 500,000 records storage',
    ],
    specs: [
      { label: 'Analyzer Type', value: 'Point-of-Care Automated Dry Chemistry Analyzer' },
      { label: 'Test Time', value: '12 minutes per reagent disc run' },
      { label: 'Sample Volume', value: '90 – 120 μL (approx. 100 μL whole blood, serum, or plasma)' },
      { label: 'Sample Type', value: 'Lithium heparin anticoagulated whole blood, serum, plasma' },
      { label: 'Detection Technology', value: 'Absorption spectroscopy + Transmission turbidimetry on microfluidic rotor discs' },
      { label: 'Calibration', value: 'Automated real-time QC with QR code calibration on every disc' },
      { label: 'Available Disc Panels', value: 'Comprehensive 19-Parameter Panel, Liver Profile, Renal Profile, Electrolytes (Na/K/Cl/Ca/P/Mg), Lipid Panel, Cardiac Markers, General Health' },
      { label: 'Display & UI', value: '7-inch color touch screen' },
      { label: 'Memory', value: 'Up to 500,000 patient test records' },
      { label: 'Connectivity', value: 'USB, LAN, LIS/HIS integration, built-in thermal printer' },
      { label: 'Dimensions & Weight', value: '25 cm × 20 cm × 30 cm | 4.6 kg' },
    ],
    warranty: '1 Year Warranty + Medwise Disc Feasibility & Clinical Orientation',
    delivery: 'Nationwide dispatch with starter reagent disc packages available',
  },

  // ==========================================
  // 2. BIOCHEMISTRY - FULLY AUTOMATED
  // ==========================================
  {
    id: 'zybio-exc-200',
    name: 'Zybio EXC 200 Fully Automated Biochemistry Analyzer',
    model: 'EXC 200',
    brand: 'Zybio',
    category: 'biochemistry',
    subcategory: 'Fully Automated Biochemistry',
    price: 1200000,
    priceFormatted: 'KSh 1,200,000',
    tagline: 'High-throughput 240 T/H desktop clinical chemistry workstation with 6-step auto cuvette wash.',
    description:
      'The Zybio EXC 200 is a fully automated, random-access clinical chemistry analyzer delivering constant 240 tests/hour throughput (single reagent). Featuring 40 refrigerated reagent positions (24h non-stop 2°C–8°C), 63 reusable optical cuvettes with automated 6-step washing, and 12 wavelengths, it is the ultimate workhorse for high-volume Kenyan hospitals.',
    badge: 'High Throughput (240 T/H)',
    highlights: [
      'Throughput: 240 tests/hour (single) / 160 tests/hour (dual reagent)',
      '40 sample positions + 40 refrigerated reagent slots (24-hour cooling)',
      '63 reaction cuvettes with 6-step automated washing station',
      '12 optical wavelengths: 340 nm to 800 nm',
      'Ultra-low carryover (≤ 0.005%) and low water consumption (≤ 5 L/H)',
    ],
    specs: [
      { label: 'System Type', value: 'Fully Automated, Random Access, STAT Priority Chemistry Analyzer' },
      { label: 'Throughput', value: 'Up to 240 tests/hour (single reagent), 160 tests/hour (dual reagent)' },
      { label: 'Sample Carousel', value: '40 sample positions (compatible with primary tubes and sample cups)' },
      { label: 'Reagent Carousel', value: '40 positions with 24-hour continuous non-stop refrigeration (2°C – 8°C)' },
      { label: 'Reaction System', value: '63 semi-permanent plastic cuvettes (5 mm optical path diameter)' },
      { label: 'Washing Station', value: '6-step automated cuvette washing with warm water and detergent' },
      { label: 'Reaction Volume', value: '90 μL – 450 μL (reduces reagent consumption per test)' },
      { label: 'Optical System', value: '12 wavelengths: 340, 380, 405, 450, 505, 546, 578, 630, 670, 700, 750, 800 nm' },
      { label: 'Probe System', value: 'Liquid level detection, collision protection, inventory monitoring' },
      { label: 'Water Consumption', value: '≤ 5 Liters / hour' },
      { label: 'Operating System', value: 'Windows 10 with bi-directional LIS integration' },
    ],
    warranty: '1 Year Warranty + Medwise Installation, Deionized Water Rig Setup & Staff Training',
    delivery: 'Nationwide Kenyan delivery and professional hospital commissioning',
  },
  {
    id: 'bioelab-as-160',
    name: 'Bioelab AS-160 Automated Clinical Chemistry Analyzer',
    model: 'AS-160',
    brand: 'Bioelab',
    category: 'biochemistry',
    subcategory: 'Fully Automated Biochemistry',
    price: 1000000,
    priceFormatted: 'KSh 1,000,000',
    tagline: 'Constant 150 T/H automated chemistry analyzer with 80 refrigerated reagent positions.',
    description:
      'The Bioelab AS-160 is a reliable, compact fully automated biochemistry analyzer providing constant 150 tests/hour throughput for both single and dual reagent assays. With an expansive 80 refrigerated reagent compartment, 44 high-transmittance reaction cuvettes, and 150 μL micro-reaction volume, it drives down operational cost per test.',
    badge: '80 Reagent Positions',
    highlights: [
      'Constant throughput: 150 tests/hour (single & double reagent)',
      '40 sample positions + 80 refrigerated reagent slots (2°C–14°C)',
      '44 high-transmittance reaction cuvettes',
      'Minimum reaction volume: 150 μL',
      'Liquid level sensing & vertical collision protection',
    ],
    specs: [
      { label: 'System Function', value: 'Fully automated, Discrete, Random Access, STAT emergency priority' },
      { label: 'Throughput', value: 'Constant 150 tests/hour' },
      { label: 'Sample Capacity', value: '40 sample positions' },
      { label: 'Reagent Capacity', value: '80 refrigerated positions with 24-hour independent cooling' },
      { label: 'Sample Volume', value: '2 – 30 μL (0.1 μL precision step)' },
      { label: 'Reagent Volume', value: '20 – 300 μL (1 μL step)' },
      { label: 'Reaction Rotor', value: '44 reaction cuvettes maintained at 37°C ± 0.1°C' },
      { label: 'Wavelengths', value: '8 standard wavelengths: 340, 405, 450, 510, 546, 578, 630, 670 nm' },
      { label: 'Probe Wash', value: 'Automatic interior and exterior probe washing, carryover < 0.1%' },
      { label: 'Software', value: 'User-friendly interface with LIS connectivity and real-time QC charts' },
    ],
    warranty: '1 Year Warranty + Medwise Preventive Calibration & Technical Service',
    delivery: 'Delivered and installed nationwide across healthcare facilities in Kenya',
  },
  {
    id: 'mindray-bs-240',
    name: 'Mindray BS-240 Clinical Chemistry Analyzer',
    model: 'BS-240',
    brand: 'Mindray',
    category: 'biochemistry',
    subcategory: 'Fully Automated Biochemistry',
    price: 1200000,
    priceFormatted: 'KSh 1,200,000',
    tagline: 'Benchmark 200 T/H automated chemistry platform (up to 400 T/H with ISE) for hospitals.',
    description:
      'The Mindray BS-240 is an industry-benchmark fully automated benchtop chemistry analyzer offering up to 200 photometric tests/hour (expandable to 400 tests/hour with optional ISE). Featuring an 80-position refrigerated carousel, reusable reaction cuvettes with automated step-washing, and 100 μL micro-reaction volume, it sets the gold standard for clinical reliability.',
    badge: 'Industry Gold Standard',
    highlights: [
      'Throughput: 200 tests/hour (up to 400 T/H with ISE)',
      'Flexible 80 reagent positions + 40 sample positions',
      'Ultra-low minimum reaction volume: 100 μL',
      '40 reusable cuvettes with automated washing system',
      'Continuous 2°C–12°C 24-hour cooling carousel',
    ],
    specs: [
      { label: 'Throughput', value: 'Up to 200 photometric tests/hour (up to 400 tests/hour with ISE module)' },
      { label: 'Reagent & Sample Tray', value: '80 reagent positions + 40 sample positions (refrigerated 2°C – 12°C)' },
      { label: 'Reaction Volume', value: '100 μL – 360 μL (drastically reduces bulk reagent costs)' },
      { label: 'Reaction Rotor', value: '40 reusable cuvettes with automated multi-step washing' },
      { label: 'Optical System', value: 'Halogen-tungsten lamp, 8 wavelengths: 340, 405, 450, 510, 546, 578, 630, 670 nm' },
      { label: 'Probe System', value: 'Liquid level detection, vertical & horizontal collision protection, clot detection' },
      { label: 'Water Consumption', value: '≤ 6.5 Liters / hour' },
      { label: 'Dimensions & Weight', value: '690 mm (L) × 580 mm (D) × 595 mm (H) | ~79 kg' },
      { label: 'Software & LIS', value: 'Advanced Windows software, bi-directional LIS integration (HL7)' },
    ],
    warranty: '1 Year Full Warranty + Medwise Calibration, RO System Advisory & Training',
    delivery: 'Nationwide Kenya delivery and clinical commissioning by certified engineers',
  },

  // ==========================================
  // 3. IMMUNOASSAY POCT
  // ==========================================
  {
    id: 'finecare-fs-113',
    name: 'Wondfo Finecare™ FS-113 FIA Meter Plus',
    model: 'FS-113',
    brand: 'Wondfo Finecare',
    category: 'immunoassay',
    subcategory: 'Immunoassay POCT',
    price: null,
    priceFormatted: 'Price on Request / Inquire',
    tagline: 'Leading fluorescence immunoassay POCT analyzer with 50+ biomarker menu.',
    description:
      'The Finecare™ FS-113 (FIA Meter Plus) is a portable fluorescence immunoassay analyzer for quantitative point-of-care testing. Delivering clinical results in 3 to 15 minutes, it supports over 50 test parameters including high-sensitivity Troponin I, NT-proBNP, D-Dimer, hs-CRP, PCT, HbA1c, and fertility hormones.',
    badge: 'Most Popular POCT FIA',
    highlights: [
      'Rapid results: 3 to 15 minutes',
      'Broad 50+ test menu: Cardiac, Inflammation, Thyroid, Fertility, Diabetes',
      'Sample types: Whole blood, serum, plasma, urine (75 μL)',
      '8-inch color LCD touchscreen & built-in thermal printer',
      'Automated ID chip lot calibration',
    ],
    specs: [
      { label: 'Technology', value: 'Fluorescence Immunoassay (FIA) Point-of-Care' },
      { label: 'Test Turnaround', value: '3 to 15 minutes (assay-dependent)' },
      { label: 'Sample Types', value: 'Whole blood, serum, plasma, urine' },
      { label: 'Sample Volume', value: 'Typically 75 μL (varies by test kit)' },
      { label: 'Test Menu', value: 'Cardiac (cTnI, NT-proBNP, D-Dimer, CK-MB, Myo), Inflammation (hs-CRP, PCT, SAA), Diabetes/Renal (HbA1c, mALB, CysC), Thyroid (TSH, T3, T4), Hormones (β-hCG, LH, FSH, Progesterone, Testosterone), Infectious (Dengue, H. Pylori)' },
      { label: 'Calibration', value: 'Automatic RFID ID chip calibration with lot-specific curve' },
      { label: 'Display', value: '8-inch color LCD touchscreen' },
      { label: 'Dimensions & Weight', value: '270 mm × 238 mm × 146 mm | 2.8 kg' },
      { label: 'Connectivity', value: 'LIS/HIS connection, USB, built-in thermal printer' },
    ],
    warranty: '1 Year Warranty + Medwise Operator Training & Cassette Supply Advisory',
    delivery: 'Immediate dispatch nationwide across Kenya',
  },
  {
    id: 'anbio-fia-analyzer',
    name: 'Anbio AF-100 Time-Resolved FIA Analyzer',
    model: 'AF-100 Series',
    brand: 'Anbio',
    category: 'immunoassay',
    subcategory: 'Immunoassay POCT',
    price: null,
    priceFormatted: 'Price on Request / Inquire',
    tagline: 'Time-Resolved Fluorescence (TRFIA) POCT analyzer with high analytical sensitivity.',
    description:
      'The Anbio AF-100 series employs Time-Resolved Fluorescence Immunoassay (TRFIA) technology to eliminate background fluorescence scatter, achieving clinical sensitivity comparable to chemiluminescence. Supporting rapid testing for cardiac, thyroid, inflammation, and hormone markers, it is ideal for triage and outpatient labs.',
    badge: 'TRFIA High Sensitivity',
    highlights: [
      'Time-Resolved Fluorescence (TRFIA) for superior signal-to-noise ratio',
      'Test time: 3 to 15 minutes (fast batch throughput up to 240 T/H)',
      'Extensive test menu: 60+ parameters across multiple clinical panels',
      '7-inch color touch screen with built-in thermal printer',
      'Automatic test cassette identification via RFID',
    ],
    specs: [
      { label: 'Technology', value: 'Time-Resolved Fluorescence Immunoassay (TRFIA)' },
      { label: 'Throughput', value: 'Up to 240 tests/hour in fast batch testing mode' },
      { label: 'Test Reaction Time', value: '3 to 15 minutes' },
      { label: 'Sample Types', value: 'Whole blood, serum, plasma' },
      { label: 'Clinical Assays', value: '60+ parameters: Cardiac markers, Thyroid function, Hormones & Fertility, Inflammation (CRP/PCT), Tumor markers, Infectious diseases' },
      { label: 'Display & UI', value: '7-inch color touchscreen interface' },
      { label: 'Memory', value: '8,000 test results (expandable)' },
      { label: 'Printer & Output', value: 'Built-in high-speed thermal printer, USB, RS-232, LIS integration' },
      { label: 'Weight & Size', value: '256 mm × 220 mm × 130 mm | 2.1 kg' },
    ],
    warranty: '1 Year Warranty + Medwise Technical Support',
    delivery: 'Available for immediate dispatch across Kenya',
  },
  {
    id: 'getein-1160',
    name: 'Getein 1160 Multi-Channel Immunofluorescence Analyzer',
    model: 'Getein 1160',
    brand: 'Getein Biotech',
    category: 'immunoassay',
    subcategory: 'Immunoassay POCT',
    price: null,
    priceFormatted: 'Price on Request / Inquire',
    tagline: 'Multi-channel POCT analyzer with 4 incubation channels + 1 STAT emergency channel.',
    description:
      'The Getein 1160 is a multi-channel immunofluorescence quantitative analyzer engineered with 4 constant-temperature (32°C) incubation channels and 1 dedicated STAT emergency channel. With a 10.1-inch HD touchscreen and lyophilized bead test technology, it handles multi-sample patient queues seamlessly.',
    badge: '4 Incubation + 1 STAT Channel',
    highlights: [
      'Channel configuration: 4 incubation channels (32°C constant) + 1 STAT emergency channel',
      'Patented lyophilized bead reagent technology',
      'Large 10.1-inch HD color touchscreen display',
      '70+ test items covering 13 clinical panels',
      'Automated cartridge collection & 100,000 results memory',
    ],
    specs: [
      { label: 'Methodology', value: 'Lateral Flow Chromatography (Immunofluorescence)' },
      { label: 'Channel Architecture', value: '4 constant-temperature incubation channels (32°C) + 1 dedicated STAT emergency channel' },
      { label: 'Reaction Time', value: '3 to 15 minutes' },
      { label: 'Sample Types', value: 'Serum, plasma, whole blood, capillary blood, urine, swab' },
      { label: 'Sample Volume', value: '10 – 200 μL (assay dependent)' },
      { label: 'Test Menu', value: '70+ test items: Cardiac (cTnI, CK-MB, Myo, NT-proBNP, D-Dimer), Infection/Inflammation (PCT, hs-CRP, SAA), Renal (mALB, NGAL, CysC), Diabetes (HbA1c), Thyroid, Fertility, Coagulation' },
      { label: 'Display & OS', value: '10.1-inch LCD touch screen (1280 × 800) running Android OS' },
      { label: 'Data Memory', value: 'Up to 100,000 patient test records' },
      { label: 'Connectivity', value: 'Ethernet (LIS/HIS), COM port, 2 × USB ports, Wi-Fi support' },
      { label: 'Dimensions & Weight', value: '299 mm (W) × 276 mm (D) × 152 mm (H) | 4.0 kg' },
    ],
    warranty: '1 Year Warranty + Medwise Installation & Staff Orientation',
    delivery: 'Nationwide dispatch with technical onboarding across Kenya',
  },

  // ==========================================
  // 4. CLINICAL MICROSCOPES
  // ==========================================
  {
    id: 'yxz-microscope',
    name: 'YXZ / XSZ Series Binocular Biological Microscope',
    model: 'YXZ / XSZ-107BN',
    brand: 'YXZ / XSZ Series',
    category: 'microscopes',
    subcategory: 'Clinical Microscopes',
    price: null,
    priceFormatted: 'Price on Request / Inquire',
    tagline: 'Durable, affordable binocular clinical microscope for routine parasitology and hematology.',
    description:
      'The YXZ / XSZ series is Kenya’s most widely deployed routine clinical and educational biological microscope. Featuring 4 achromatic objectives (4X, 10X, 40X, 100X Oil), a double-layer mechanical stage with coaxial coarse/fine focusing, and bright variable illumination, it is the standard for stool, urine, and blood smear analysis.',
    badge: 'Kenyan Clinical Standard',
    highlights: [
      'Achromatic objectives: 4X, 10X, 40X(S), 100X(S, Oil)',
      'Magnification: 40X to 1600X (with WF10X & WF16X eyepieces)',
      'Double-layer mechanical stage (140 × 140 mm) with specimen clamp',
      'Coaxial coarse and fine focusing (0.002 mm precision division)',
      'Abbe Condenser N.A. 1.25 with iris diaphragm & filter holder',
    ],
    specs: [
      { label: 'Viewing Head', value: 'Sliding binocular head, 45° inclined, 360° rotatable, interpupillary 55–75 mm' },
      { label: 'Eyepieces', value: 'Wide Field WF10X and WF16X' },
      { label: 'Achromatic Objectives', value: '4X/0.10, 10X/0.25, 40X/0.65 (Spring), 100X/1.25 (Spring, Oil)' },
      { label: 'Total Magnification', value: '40X – 1600X' },
      { label: 'Mechanical Stage', value: 'Double layer mechanical stage: 140 × 140 mm, moving range 75 × 50 mm' },
      { label: 'Focusing Mechanism', value: 'Coaxial coarse and fine adjustment knobs with tension control and safety stop' },
      { label: 'Condenser', value: 'Abbe condenser N.A. 1.25 with iris diaphragm and color filter' },
      { label: 'Illumination', value: 'Variable brightness LED or 6V 20W halogen lamp (220V mains)' },
      { label: 'Frame & Build', value: 'Heavy cast-metal rigid stand with anti-fungus treated optics' },
    ],
    warranty: '1 Year Warranty + Medwise Optical Alignment & Lens Care Advisory',
    delivery: 'In stock for immediate delivery in Kisumu, Nairobi, and countrywide',
  },
  {
    id: 'olympus-cx-21',
    name: 'Olympus CX21 Biological Microscope',
    model: 'CX21',
    brand: 'Olympus',
    category: 'microscopes',
    subcategory: 'Clinical Microscopes',
    price: null,
    priceFormatted: 'Price on Request / Inquire',
    tagline: 'Renowned UIS2 infinity optical clarity and legendary mechanical durability.',
    description:
      'The Olympus CX21 is a globally respected biological microscope renowned for its UIS2 infinity-corrected optics, crystal-clear flat field images, and exceptional mechanical longevity. Built to endure decades of continuous laboratory workload, it remains a gold standard for hospital diagnostic pathology.',
    badge: 'UIS2 Optical System',
    highlights: [
      'UIS2 Universal Infinity-corrected optical system',
      'Plan Achromat objectives (4X, 10X, 40X, 100X Oil)',
      'Rackless mechanical stage with no protruding guide wire',
      'Abbe Condenser N.A. 1.25 with aperture iris diaphragm',
      '6V 20W halogen / LED variable brightness illumination',
    ],
    specs: [
      { label: 'Optical System', value: 'UIS2 (Universal Infinity System) infinity-corrected optics' },
      { label: 'Viewing Head', value: 'Binocular tube, 30° inclined, 360° rotatable, interpupillary distance 48–75 mm' },
      { label: 'Eyepieces', value: '10X with Field Number (FN) 18' },
      { label: 'Objectives', value: 'Plan Achromat 4X (N.A. 0.10), 10X (N.A. 0.25), 40X (N.A. 0.65), 100X Oil (N.A. 1.25)' },
      { label: 'Revolving Nosepiece', value: 'Quadruple inward-facing nosepiece' },
      { label: 'Stage', value: 'Wire-movement mechanical stage (rackless), 120 × 132 mm with specimen holder' },
      { label: 'Focusing', value: 'Coaxial coarse and fine focusing knobs with focus limit stop to protect slides' },
      { label: 'Condenser', value: 'Abbe condenser N.A. 1.25 with aperture diaphragm' },
      { label: 'Illumination', value: '6V 20W halogen lamp or LED light source with variable intensity' },
      { label: 'Optics Protection', value: 'Anti-fungus treatment on all optical components for humid tropical climates' },
    ],
    warranty: '1 Year Warranty + Medwise Precision Calibration & Alignment Certificate',
    delivery: 'Supplied across Kenya with complete dust cover and immersion oil kit',
  },
  {
    id: 'olympus-cx-23',
    name: 'Olympus CX23 Ergonomic LED Biological Microscope',
    model: 'CX23',
    brand: 'Olympus',
    category: 'microscopes',
    subcategory: 'Clinical Microscopes',
    price: null,
    priceFormatted: 'Price on Request / Inquire',
    tagline: 'Modern ergonomic design with daylight-balanced 20,000-hour LED illumination & FN 20.',
    description:
      'The Olympus CX23 is the advanced evolution of the CX series, featuring a wide Field Number 20, long-life LED illumination (20,000 hours, daylight-balanced 5500K color temperature), and an ergonomic lightweight frame (5.9 kg) with built-in carrying grips. Designed for modern clinical labs, it delivers crisp, high-contrast imagery.',
    badge: 'Daylight LED + FN 20',
    highlights: [
      'Olympus Infinity Optical System with Plan Achromat anti-fungus optics',
      'Built-in energy-efficient LED light source (20,000-hour lifespan)',
      'Large Field Number (FN) 20 for wider diagnostic view',
      'Ergonomic lightweight design (5.9 kg) with non-slip carrying grips',
      'Rackless stage and focus lock mechanism to prevent slide breakage',
    ],
    specs: [
      { label: 'Optical System', value: 'Olympus Infinity Optical System' },
      { label: 'Viewing Head', value: 'Binocular tube, 30° inclined, interpupillary adjustment 48–75 mm, eyepoint height adjustment' },
      { label: 'Eyepieces', value: '10X with wide Field Number (FN) 20' },
      { label: 'Objectives', value: 'Plan Achromat 4X (N.A. 0.10), 10X (N.A. 0.25), 40X (N.A. 0.65), 100X Oil (N.A. 1.25)' },
      { label: 'Illumination', value: 'Built-in transmitted LED illumination, 0.5W, daylight-balanced color temperature (approx. 20,000 hr life)' },
      { label: 'Stage', value: 'Rackless wire-driven mechanical stage (120 × 132 mm) with specimen holder' },
      { label: 'Focusing Mechanism', value: 'Coaxial coarse and fine adjustment; coarse stroke 15 mm; fine division 2.5 μm; focus lock' },
      { label: 'Condenser', value: 'Abbe condenser N.A. 1.25 with position guide markings for respective objectives' },
      { label: 'Security & Safety', value: 'Kensington lock compatible slot; integrated power cord storage' },
      { label: 'Weight', value: 'Approximately 5.9 kg' },
    ],
    warranty: '1 Year Warranty + Medwise Technical Support & Certificate of Calibration',
    delivery: 'Available for immediate dispatch across Kisumu, Nairobi, and all counties',
  },

  // ==========================================
  // 5. OTHER LAB EQUIPMENT
  // ==========================================
  {
    id: 'laboratory-incubator',
    name: 'Bacteriological Laboratory Incubator',
    model: 'DHP / DNP Series',
    brand: 'Clinical Grade',
    category: 'lab-equipment',
    subcategory: 'Laboratory Equipment',
    price: null,
    priceFormatted: 'Price on Request / Inquire',
    tagline: 'Digital PID temperature-controlled incubator for microbiology culture and diagnostic incubation.',
    description:
      'Essential for microbiology, bacteriology, and clinical diagnostic incubation, this benchtop laboratory incubator features a digital PID microcomputer controller, high-grade stainless steel interior, and a tempered glass inner observation door to observe culture plates without losing internal heat.',
    badge: 'Microbiology Essential',
    highlights: [
      'Capacity: 30L to 50L chambers available',
      'Temperature range: Ambient +5°C to 65°C (±0.1°C precision)',
      'Digital PID microcomputer temperature controller',
      'Corrosion-resistant SUS304 stainless steel interior chamber',
      'Dual-door design with tempered glass observation window',
    ],
    specs: [
      { label: 'Capacity Options', value: '30 Liters / 50 Liters benchtop models' },
      { label: 'Temperature Range', value: 'Ambient +5°C to 65°C' },
      { label: 'Temperature Fluctuations', value: '±0.5°C | Resolution: 0.1°C' },
      { label: 'Controller', value: 'Microprocessor PID controller with digital LED display and timer (0–9999 min)' },
      { label: 'Inner Chamber', value: 'Mirror stainless steel SUS304 with semi-circular corners for easy decontamination' },
      { label: 'Observation Door', value: 'Independent tempered glass inner door allows viewing without thermal disruption' },
      { label: 'Safety Protection', value: 'Independent over-temperature limit alarm and auto power cut-off' },
      { label: 'Shelves', value: '2 adjustable stainless steel grid shelves' },
      { label: 'Power Supply', value: 'AC 220V ± 10%, 50/60 Hz' },
    ],
    warranty: '1 Year Warranty + Medwise Temperature Calibration Certification',
    delivery: 'Nationwide delivery with engineer verification across Kenya',
  },
  {
    id: 'clinical-centrifuges',
    name: 'Clinical Laboratory Benchtop Centrifuge',
    model: '80-2C / TD4 Digital Series',
    brand: 'Clinical Grade',
    category: 'lab-equipment',
    subcategory: 'Laboratory Equipment',
    price: null,
    priceFormatted: 'Price on Request / Inquire',
    tagline: 'Quiet brushless centrifuge for rapid serum, plasma, and urine sample separation.',
    description:
      'High-performance benchtop laboratory centrifuge designed for routine clinical sample preparation (blood serum, plasma separation, and urine sediment). Available in traditional and modern digital brushless motor formats (up to 4000 RPM / 2150 x g) with automatic lid lock security.',
    badge: 'Serum & Plasma Separation',
    highlights: [
      'Speed range: Up to 4000 RPM (RCF approx. 2150 × g)',
      'Rotor capacity: 6 × 15 mL or 8 × 15 mL / 10 mL tubes',
      'Maintenance-free brushless DC motor (< 55 dB noise level)',
      'Digital LCD display for speed (RPM), RCF, and timer',
      'Electronic safety lid interlock and emergency release',
    ],
    specs: [
      { label: 'Maximum Speed', value: '4000 RPM (Adjustable in 100 RPM increments)' },
      { label: 'Max RCF', value: '2150 × g' },
      { label: 'Rotor Capacity', value: '8 × 15 mL angle rotor (supports standard vacutainers 5 mL, 7 mL, 10 mL, 15 mL)' },
      { label: 'Motor Type', value: 'Maintenance-free brushless DC motor (zero carbon dust)' },
      { label: 'Timer Range', value: '1 to 99 minutes or continuous mode' },
      { label: 'Safety Interlocks', value: 'Electronic lid lock prevents opening while rotor is in motion; overspeed sensor' },
      { label: 'Chamber Material', value: 'Heavy-duty steel casing with protective inner containment ring' },
      { label: 'Noise Level', value: '≤ 55 dB at maximum RPM' },
      { label: 'Power Supply', value: '220V 50Hz' },
    ],
    warranty: '1 Year Warranty + Medwise Tachometer Speed Calibration Certificate',
    delivery: 'Fast dispatch from Kisumu HQ and Nairobi Field Hub',
  },
  {
    id: 'roller-mixer',
    name: 'Blood Tube Roller Mixer',
    model: 'TR-6 Series',
    brand: 'Clinical Grade',
    category: 'lab-equipment',
    subcategory: 'Laboratory Equipment',
    price: null,
    priceFormatted: 'Price on Request / Inquire',
    tagline: 'Simultaneous rocking and rolling motion for thorough, gentle blood anticoagulation mixing.',
    description:
      'The 6-roller blood tube mixer provides gentle, highly efficient mixing of hematology whole blood samples in EDTA, heparin, and citrate tubes. Combining simultaneous 360° rolling and gentle axial rocking motions, it prevents cell settling and clot formation without damaging red blood cells.',
    badge: 'Hematology Essential',
    highlights: [
      '6-roller continuous & rocking motion for thorough mixing',
      'Speed range: 10 to 80 RPM adjustable',
      'Accommodates 8 mm to 32 mm diameter blood collection tubes',
      'Continuous duty motor built for all-day clinical operation',
      'Spill-proof easy-clean roller surfaces',
    ],
    specs: [
      { label: 'Roller Count', value: '6 rollers (Length: 280 mm each)' },
      { label: 'Motion', value: 'Simultaneous rocking (±5°) and rolling (360°)' },
      { label: 'Speed Range', value: '10 – 80 RPM adjustable' },
      { label: 'Tube Accommodation', value: 'Standard blood collection tubes (diameter 8–32 mm, length up to 200 mm)' },
      { label: 'Operation Modes', value: 'Continuous operation or timed mode (1–120 min)' },
      { label: 'Maximum Load', value: 'Up to 4 kg' },
      { label: 'Motor', value: 'High-torque DC brushless motor for silent, vibration-free operation' },
      { label: 'Dimensions & Weight', value: '450 mm × 260 mm × 120 mm | 4.5 kg' },
    ],
    warranty: '1 Year Warranty + Medwise Technical Support',
    delivery: 'Immediate dispatch nationwide across Kenya',
  },
  {
    id: 'vdrl-shaker',
    name: 'VDRL / Orbital Laboratory Shaker',
    model: 'VR-100 / OS Series',
    brand: 'Clinical Grade',
    category: 'lab-equipment',
    subcategory: 'Laboratory Equipment',
    price: null,
    priceFormatted: 'Price on Request / Inquire',
    tagline: 'Adjustable 0–210 RPM orbital rotator for VDRL, syphilis RPR, blood grouping, and agglutination assays.',
    description:
      'Engineered specifically for serological agglutination testing, VDRL test for syphilis, blood grouping, and latex agglutination cards. Features an adjustable orbital speed of 0 to 210 RPM, a non-slip platform with spring clips, and an integrated 60-minute mechanical timer.',
    badge: 'Serology Workhorse',
    highlights: [
      'Speed range: 0 to 210 RPM adjustable',
      'Orbital diameter: 22 mm for optimal agglutination vortex',
      'Platform: 315 × 225 mm with non-slip rubber pad and spring clips',
      'Integrated mechanical timer: 0 to 60 minutes or continuous',
      'Stable heavy-duty base prevents bench creeping during rotation',
    ],
    specs: [
      { label: 'Rotation Speed', value: '0 – 210 RPM continuously variable' },
      { label: 'Orbit Diameter', value: '22 mm' },
      { label: 'Platform Dimensions', value: '315 mm × 225 mm with elastic hold-down springs' },
      { label: 'Timer', value: '0 – 60 minutes or continuous run' },
      { label: 'Applications', value: 'VDRL / RPR Syphilis test, ABO blood grouping, Widal test, Rheumatoid factor, Latex agglutination' },
      { label: 'Weight & Power', value: 'Approx. 4.0 kg | AC 220V 50Hz' },
    ],
    warranty: '1 Year Warranty + Medwise Advisory',
    delivery: 'In stock for countrywide dispatch in Kenya',
  },
  {
    id: 'hot-air-oven',
    name: 'Laboratory Hot Air Sterilizing & Drying Oven',
    model: 'GRX / DHG Series',
    brand: 'Clinical Grade',
    category: 'lab-equipment',
    subcategory: 'Laboratory Equipment',
    price: null,
    priceFormatted: 'Price on Request / Inquire',
    tagline: 'Forced-air convection dry heat sterilizer (50°C–250°C) for laboratory glassware and instruments.',
    description:
      'Heavy-duty forced-air convection hot air oven designed for dry heat sterilization of laboratory glassware, pipettes, metal surgical instruments, and sample drying. Equipped with digital microcomputer temperature control up to 250°C and a stainless steel inner chamber.',
    badge: 'Sterilization & Drying',
    highlights: [
      'Working temperature: 50°C to 250°C (±1°C precision)',
      'Forced air convection fan for uniform heat distribution',
      'High-grade SUS304 mirror stainless steel interior',
      'Dual digital LED display for set and actual temperature',
      'Independent over-temperature thermal safety cutout',
    ],
    specs: [
      { label: 'Temperature Range', value: '50°C – 250°C' },
      { label: 'Air Circulation', value: 'Electric fan-forced convection system' },
      { label: 'Capacity Options', value: '30L, 45L, 65L, 125L models available' },
      { label: 'Chamber Material', value: 'SUS304 mirror stainless steel with rounded cleanable corners' },
      { label: 'Controller', value: 'Intelligent PID microcomputer with timing function' },
      { label: 'Safety Protections', value: 'Over-temperature acoustic-optic alarm and independent temperature limiter' },
      { label: 'Door Seal', value: 'High-temperature resistant silicone gasket with double glass viewing window' },
      { label: 'Power', value: 'AC 220V 50Hz' },
    ],
    warranty: '1 Year Warranty + Medwise Heat Uniformity Calibration',
    delivery: 'Nationwide dispatch and hospital installation across Kenya',
  },
  {
    id: 'laboratory-fridge',
    name: 'Medical & Laboratory Refrigerator (2°C – 8°C)',
    model: 'MPC / YC Series',
    brand: 'Clinical Grade',
    category: 'lab-equipment',
    subcategory: 'Laboratory Equipment',
    price: null,
    priceFormatted: 'Price on Request / Inquire',
    tagline: 'Strict 2°C–8°C forced-air medical pharmacy & laboratory refrigerator with digital temperature alarms.',
    description:
      'Designed specifically for the strict preservation of laboratory reagents, blood control materials, vaccines, and diagnostic test kits. Featuring microcomputer temperature control at 2°C to 8°C, forced-air cooling, anti-condensation heated glass door, and audible/visual alarms for high/low temperature and power disruption.',
    badge: 'Reagent Cold-Chain Essential',
    highlights: [
      'Strict 2°C to 8°C internal temperature stability',
      'Forced-air circulation cooling prevents freezing cold-spots',
      'High/Low temperature, door ajar, and power failure alarms',
      'Heated double-pane glass door eliminates condensation fog',
      'Eco-friendly CFC-free refrigerant and energy-efficient compressor',
    ],
    specs: [
      { label: 'Temperature Range', value: '2°C to 8°C (Factory set at 4°C with ±1°C accuracy)' },
      { label: 'Cooling System', value: 'Forced air circulation with high-efficiency hermetic compressor' },
      { label: 'Capacity Range', value: 'Available in 130L, 260L, 315L, and 395L capacities' },
      { label: 'Defrosting', value: 'Automatic intelligent cycle defrost' },
      { label: 'Alarms', value: 'Audible buzzer & visual strobe: High/Low temperature, Sensor error, Door ajar, Power outage' },
      { label: 'Controller & Display', value: 'Microprocessor controller with 0.1°C resolution digital LED display' },
      { label: 'Door', value: 'Heated double-glazed Low-E glass door with safety lock and interior LED light' },
      { label: 'Refrigerant', value: 'CFC-free R600a / R134a environmentally safe refrigerant' },
      { label: 'Shelving', value: 'Adjustable plastic-coated wire shelves with inventory label holders' },
    ],
    warranty: '1 Year Warranty + Medwise Cold Chain Temperature Mapping Certification',
    delivery: 'Delivered and safely positioned anywhere in Kenya',
  },
  {
    id: 'micropipettes',
    name: 'Precision Adjustable Single Channel Micropipettes',
    model: '10–100 μL & 100–1000 μL',
    brand: 'Clinical Grade',
    category: 'lab-equipment',
    subcategory: 'Laboratory Equipment',
    price: null,
    priceFormatted: 'Price on Request / Inquire',
    tagline: 'ISO 8655 compliant ergonomic variable pipettes with autoclavable tip cones.',
    description:
      'High-precision variable volume single-channel micropipettes available in standard clinical laboratory ranges: 10–100 μL and 100–1000 μL. Featuring an ultra-lightweight ergonomic design, low plunger force to prevent hand fatigue (RSI), clear digital volume counter, and autoclavable tip ejector cone.',
    badge: 'ISO 8655 Calibrated',
    highlights: [
      'Available ranges: 10–100 μL and 100–1000 μL',
      'Clear digital volume indicator display with locking mechanism',
      'Fully autoclavable lower tip cone (121°C, 20 min)',
      'Ultra-lightweight ergonomic handle with smooth plunger operation',
      'Universal tip cone compatible with all standard yellow and blue tips',
    ],
    specs: [
      { label: 'Volume Ranges', value: '10 – 100 μL (0.1 μL increments) | 100 – 1000 μL (1 μL increments)' },
      { label: 'Standard Compliance', value: 'Factory calibrated in accordance with ISO 8655 / DIN 12650' },
      { label: 'Plunger Mechanism', value: 'Dual-action light plunger stroke with dedicated tip ejection button' },
      { label: 'Volume Adjustment', value: 'Rotary push-button with audible click lock' },
      { label: 'Autoclavability', value: 'Lower manifold and tip cone fully autoclavable at 121°C for 20 minutes' },
      { label: 'Chemical Resistance', value: 'Engineered polymers resistant to clinical laboratory solvents and acids' },
      { label: 'Calibration Certificate', value: 'Individual gravimetric calibration certificate included' },
    ],
    warranty: '1 Year Warranty + Medwise Gravimetric Verification & Calibration Check',
    delivery: 'In stock for immediate dispatch nationwide in Kenya',
  },

  // ==========================================
  // 6. CONSUMABLES
  // ==========================================
  {
    id: 'microscope-slides',
    name: 'Clinical Microscope Glass Slides (Plain & Frosted)',
    model: '7101 Plain / 7102 Frosted',
    brand: 'Clinical Grade',
    category: 'consumables',
    subcategory: 'Laboratory Consumables',
    price: null,
    priceFormatted: 'Price on Request / Inquire',
    tagline: 'Pre-cleaned, lint-free optical clarity glass slides with 90° ground or beveled safety edges.',
    description:
      'Standard 25.4 × 76.2 mm (1" × 3") clinical microscope slides manufactured from premium float glass. Available in 7101 Plain (clear on both ends) and 7102 Single-End Frosted (sandblasted frosted writing surface for permanent pencil or marker sample labeling). Ideal for blood smears, urine microscopy, and histopathology.',
    badge: 'High Optical Clarity',
    highlights: [
      'Sizes: Standard 25.4 × 76.2 mm (1" × 3"), thickness 1.0–1.2 mm',
      'Types: 7101 Plain Glass & 7102 Single Frosted End',
      'Pre-cleaned, degreased, ready for immediate smear preparation',
      'Ground safety edges to prevent technologist glove punctures',
      'Packed in moisture-proof vacuum cellophane packs (50 or 72 pcs/box)',
    ],
    specs: [
      { label: 'Dimensions', value: '25.4 mm × 76.2 mm (1 inch × 3 inches)' },
      { label: 'Thickness', value: '1.0 mm – 1.2 mm' },
      { label: 'Glass Material', value: 'Premium high-transmittance optical clear soda-lime float glass' },
      { label: 'Edge Finish', value: '90° ground safety edges or 45° beveled corners' },
      { label: 'Surface Finish', value: 'Pre-cleaned, hydrophilically balanced for uniform blood smear spreading' },
      { label: 'Variants', value: 'Model 7101 (Plain) | Model 7102 (Single-end frosted on one side for labeling)' },
      { label: 'Packaging', value: '50 pcs/box or 72 pcs/box; 50 boxes/carton' },
    ],
    warranty: 'Guaranteed optical clarity and pre-cleaned standard',
    delivery: 'Bulk and retail supply across Kisumu, Nairobi, and countrywide',
  },
  {
    id: 'cover-slips',
    name: 'Microscope Cover Slips (Cover Glasses)',
    model: '22×22 mm & 24×24 mm',
    brand: 'Clinical Grade',
    category: 'consumables',
    subcategory: 'Laboratory Consumables',
    price: null,
    priceFormatted: 'Price on Request / Inquire',
    tagline: 'Ultra-thin No. 1 borosilicate glass coverslips for crystal-clear slide examination.',
    description:
      'Microscope cover slips manufactured from pure, non-corrosive borosilicate glass. With uniform No. 1 thickness (0.13–0.17 mm), they prevent specimen drying, protect objective lenses from immersion oil contact, and ensure bubble-free optical clarity during high-power 40X and 100X microscopy.',
    badge: 'Specimen Protection',
    highlights: [
      'Standard sizes: 22 × 22 mm and 24 × 24 mm',
      'Uniform No. 1 thickness (0.13 mm to 0.17 mm)',
      'Free from bubbles, scratches, and striations',
      'Non-sticking individual slide separation with interleaving paper',
      'Packed in plastic dispenser boxes of 100 pcs',
    ],
    specs: [
      { label: 'Standard Sizes', value: '22 mm × 22 mm | 24 mm × 24 mm | 24 mm × 50 mm' },
      { label: 'Thickness Grade', value: 'No. 1 (0.13 mm to 0.17 mm)' },
      { label: 'Material', value: 'Pure non-corrosive optical borosilicate glass' },
      { label: 'Features', value: 'Uniform flatness, non-fogging, non-sticking' },
      { label: 'Packaging', value: '100 pcs per plastic dispenser box; 10 boxes per vacuum pack' },
    ],
    warranty: 'Quality inspected for laboratory microscopy use',
    delivery: 'Nationwide dispatch in Kenya',
  },
  {
    id: 'yellow-tips',
    name: 'Universal Pipette Tips 200 μL (Yellow Tips)',
    model: '200 μL Universal',
    brand: 'Clinical Grade',
    category: 'consumables',
    subcategory: 'Laboratory Consumables',
    price: null,
    priceFormatted: 'Price on Request / Inquire',
    tagline: 'Precision-molded virgin polypropylene yellow tips compatible with all standard micropipettes.',
    description:
      'Universal 200 μL yellow pipette tips manufactured from medical-grade virgin polypropylene. Featuring hydrophobic low-retention internal surfaces and precision-molded graduated markings, they ensure maximum liquid pipetting accuracy for hematology, biochemistry, and PCR workflows.',
    badge: 'Universal Fit',
    highlights: [
      'Volume capacity: 200 μL universal pipette tips',
      'Medical-grade virgin polypropylene (PP) with color-coded yellow dye',
      'Hydrophobic inner surface minimizes sample retention',
      'Autoclavable at 121°C for 20 minutes',
      'Available in bulk economy bags (1,000 pcs) or 96-well racked boxes',
    ],
    specs: [
      { label: 'Volume Capacity', value: '0.5 – 200 μL' },
      { label: 'Material', value: 'Medical-grade virgin polypropylene (PP)' },
      { label: 'Color', value: 'Standard yellow color-coded' },
      { label: 'Graduation', value: 'Precision molded graduation lines for volume verification' },
      { label: 'Purity', value: 'RNase, DNase, Pyrogen, and endotoxin free' },
      { label: 'Autoclavability', value: 'Autoclavable at 121°C for 20 minutes at 1 bar' },
      { label: 'Compatibility', value: 'Universal cone fit for Gilson, Eppendorf, Biohit, Thermo, and Medwise pipettes' },
      { label: 'Packaging', value: '1,000 pcs/bag or 96-tip autoclavable racks' },
    ],
    warranty: 'Guaranteed leak-proof seal and universal fit',
    delivery: 'Bulk orders dispatched across Kenya same-day',
  },
  {
    id: 'vacutainer-tubes',
    name: 'Vacuum Blood Collection Tubes (Vacutainer Series)',
    model: 'Purple, Red, Yellow & Blue Top',
    brand: 'Clinical Grade',
    category: 'consumables',
    subcategory: 'Laboratory Consumables',
    price: null,
    priceFormatted: 'Price on Request / Inquire',
    tagline: 'Standardized ISO color-coded vacuum blood collection tubes for hematology, chemistry & coagulation.',
    description:
      'Sterile medical PET and glass vacuum blood collection tubes color-coded to international ISO and CLSI standards. Featuring precise negative draw vacuum, leak-proof safety rubber stoppers, and standardized additives for Complete Blood Count, Clinical Chemistry, Serology, and Coagulation testing.',
    badge: 'ISO / CLSI Standardized',
    highlights: [
      'Purple Top (EDTA K2/K3): For Complete Blood Count (CBC) and hematology',
      'Red Top (Plain / Clot Activator): For serum clinical chemistry and serology',
      'Yellow Top (SST Gel & Clot Activator): For clean serum separation in biochemistry',
      'Blue Top (Sodium Citrate 3.2% 1:9): For PT, APTT, and INR coagulation analysis',
      'Precise vacuum draw volume (2 mL, 3 mL, 4 mL, 5 mL)',
    ],
    specs: [
      { label: 'Purple Top Tube', value: 'Additive: K2 EDTA / K3 EDTA | Volume: 2 mL, 3 mL, 4 mL | Use: Routine CBC, Blood grouping, HbA1c' },
      { label: 'Red Top Tube', value: 'Additive: Plain / Silica Clot Activator | Volume: 4 mL, 5 mL, 10 mL | Use: Serum chemistry, Blood donor screening, Serology' },
      { label: 'Yellow Top Tube (SST)', value: 'Additive: Inert Polymer Barrier Gel & Clot Activator | Volume: 4 mL, 5 mL | Use: Clinical chemistry, Hormone assays, Infectious disease serology' },
      { label: 'Blue Top Tube', value: 'Additive: 3.2% (0.109 mol/L) Sodium Citrate in 1:9 ratio | Volume: 1.8 mL, 2.7 mL | Use: Coagulation PT/INR, APTT, D-Dimer' },
      { label: 'Tube Material', value: 'Shatter-proof medical PET (Polyethylene Terephthalate) or borosilicate glass' },
      { label: 'Cap Design', value: 'Color-coded safety rubber stopper with plastic safety shield to prevent aerosol spray' },
      { label: 'Sterility & Shelf Life', value: 'Sterile radiation sealed; 18–24 months shelf life' },
      { label: 'Packaging', value: '100 tubes per foam tray / rack; 1,200 tubes per master carton' },
    ],
    warranty: 'Strict ISO vacuum draw compliance guaranteed',
    delivery: 'Bulk hospital cartons and mixed clinic packs available across Kenya',
  },
  {
    id: 'medical-gloves',
    name: 'Medical Examination Gloves (Latex & Nitrile Powder-Free)',
    model: 'Powder-Free Examination',
    brand: 'Clinical Grade',
    category: 'consumables',
    subcategory: 'Laboratory Consumables',
    price: null,
    priceFormatted: 'Price on Request / Inquire',
    tagline: 'High-tensile powder-free examination gloves with textured fingertips for tactile clinical sensitivity.',
    description:
      'Premium medical-grade examination gloves available in Powder-Free Natural Rubber Latex and Powder-Free Synthetic Nitrile (ideal for personnel and patients with Type I latex allergies). Featuring textured fingertips for superior grip, beaded cuffs to prevent roll-down, and rigorous AQL 1.5 pinhole inspection standards.',
    badge: 'AQL 1.5 Medical Grade',
    highlights: [
      'Variants: Powder-Free Natural Rubber Latex & 100% Synthetic Nitrile',
      'Textured fingertips provide excellent wet and dry grip',
      'Ambidextrous with beaded cuff for easy donning and tear resistance',
      'Compliant with medical regulatory standards (EN 455, ASTM D3578 / D6319)',
      'Box of 100 pieces (50 pairs); Available in XS, S, M, L, XL',
    ],
    specs: [
      { label: 'Material Options', value: 'Natural Rubber Latex (Powder-Free) or Synthetic Nitrile (Latex-Free, Powder-Free)' },
      { label: 'Quality Standard', value: 'Medical examination grade AQL 1.5 pinhole inspection' },
      { label: 'Surface Texture', value: 'Micro-textured fingertips for fine instrument and pipette handling' },
      { label: 'Cuff Style', value: 'Beaded reinforced cuff to prevent roll-down' },
      { label: 'Sizes Available', value: 'Extra Small (XS), Small (S), Medium (M), Large (L), Extra Large (XL)' },
      { label: 'Color', value: 'Latex: Natural White / Off-White | Nitrile: Medical Blue' },
      { label: 'Packaging', value: '100 pcs per dispenser box (by weight); 10 boxes per master carton (1,000 pcs)' },
    ],
    warranty: 'Certified AQL 1.5 medical examination standard',
    delivery: 'Bulk clinic and hospital delivery dispatched nationwide across Kenya',
  },
];

/**
 * Generates the WhatsApp click-to-chat URL with a prefilled inquiry/purchase message
 * including the specific canonical product link.
 */
export function getProductWhatsAppUrl(
  product: Product,
  options?: { customBaseUrl?: string }
): string {
  const baseUrl = (options?.customBaseUrl || SITE_CONFIG.url || 'https://www.medwisetechnicalconsulting.co.ke').replace(/\/$/, '');
  const productUrl = `${baseUrl}/products#${product.id}`;

  const priceText = product.price
    ? `Listed Price: ${product.priceFormatted}`
    : `Listed Price: Inquire for Quote / Competitive Hospital Rate`;

  const message = [
    `Hello Medwise Technical Consulting,`,
    ``,
    `I would like to BUY / INQUIRE via WhatsApp regarding:`,
    `• Product: ${product.name} (${product.model})`,
    `• Category: ${product.subcategory}`,
    `• ${priceText}`,
    `• Product Link: ${productUrl}`,
    ``,
    `Please provide availability, delivery details to my facility, and purchasing guidance. Thank you!`,
  ].join('\n');

  return `https://wa.me/${SITE_CONFIG.whatsappNumber}?text=${encodeURIComponent(message)}`;
}
